<?php

use Illuminate\Database\Seeder;

class ApartmentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::table('apartments')->truncate();
        \Illuminate\Support\Facades\DB::table('apartments')->insert([
            [
                'id' => 1,
                'ten' => 'chung cu 1',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 2,
                'ten' => 'chung cu 2',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 3,
                'ten' => 'chung cu 3',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 4,
                'ten' => 'chung cu 4',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 5,
                'ten' => 'chung cu 5',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 6,
                'ten' => 'chung cu 6',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 7,
                'ten' => 'chung cu 7',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 8,
                'ten' => 'chung cu 8',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 9,
                'ten' => 'chung cu 9',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 10,
                'ten' => 'chung cu 10',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 11,
                'ten' => 'chung cu 11',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 12,
                'ten' => 'chung cu 12',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 13,
                'ten' => 'chung cu 13',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 14,
                'ten' => 'chung cu 14',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 15,
                'ten' => 'chung cu 15',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 16,
                'ten' => 'chung cu 16',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 17,
                'ten' => 'chung cu 17',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 18,
                'ten' => 'chung cu 18',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 19,
                'ten' => 'chung cu 19',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ],
            [
                'id' => 20,
                'ten' => 'chung cu 20',
                'diachi' => 'Xuan la - Ha noi',
                'giaban' => 500,
                'thongtinchung' => 'chung cu ha noi',
                'chitiet' => 'cao cap',
                'hinh' => 'http://staticl.enternews.vn/images/big/pic1.png',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'trangthai' => 1,
            ]
        ]);
    }
}
